### ISSUE TITLE
Plug-in working for only one Project

### ISSUE THREAD

**Issue by ghousenaren** [msldn/Jenkins-Diawi-Plugin#1]
If we use the plugin for first time in any project its working fine. But if  we used this plugin another project  its resetting  all changes  with previous project where this plugin have already used.
 
Reproducible Steps:
 
1.       Create a project add the diawi plugin.
2.       Create another project and add the diawi plugin. Now you can observe all the project settings has been replaced with previous project.
 
 
Can you please look into this issue once?

**Comment by msldn** [comment]
Are you using the latest version?
would you please also send some screen shots on the configuration of both jobs

**Comment by ghousenaren** [comment]
Thanks it got fixed.
